### ISSUE TITLE
 Unsupported chain id: 1. Supported chain ids are: 56,4,97

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [Linch1/Web3NextjsAuth#1]
error 1 : Unsupported chain id: 1. Supported chain ids are: 56,4,97;
warn 1 : [next-auth][warn][NO_SECRET] 

how to fix it ?

**Comment by Linch1** [comment]
error 1 : Unsupported chain id: 1. Supported chain ids are: 56,4,97;
you can fix this by going to the file `https://github.com/Linch1/Web3NextjsAuth/blob/master/web3Connectors/connectors.js` and adding the chain where you want to connect, here you can find some https://chainlist.org/ 

else you can switch to binance smart chain inside your wallet and you should be able to connect the wallet.

For the warn i don't know right now, maybe try checking it on nextjs docs, i'll see it once i've time :)
